YosysHQ/picorv32

Makefile
axi4_memory.v
picorv32_wrapper.v
testbench.v

Some testbench refactoring to increase modularity and prepare for a Verilator testbench. I already have a verilator testbench in the picorv32 version that is found in the FuseSoC standard core library. This testbench however has dependencies on other cores in the library, and might need some changes to be helpful in a non-FuseSoC environment
This series also introduces some new plusargs to change firmware, verbosity and axi delay randomization without recompiling the testbench

Refactoring

---

picorv32.v

This fixes #8
It leaves two potentially unanswered problems/new issues:
- Instructions such as `sbreak` take at least 16 cycles to trigger an IRQ, as they wait for PCPI timeout. Writing logic to IRQ immediately on `sbreak` and potentially `scall` instructions might be desirable. Alternatively, an external PCPI module could do this, but would then have to use a different IRQ line.
- I haven't examined how an sbreak or illegal instruction would be handled inside the ISR, but trapping seems logical.

Deassert pcpi_valid upon asserting sbreak IRQ

---

picorv32.v

On Array 10, the very minor change below has the following impact:
- Uses 3 DSPs instead of 6
- Uses the output registers of the DSPs instead of using random logic output registers for rd. 
- As a result, timing improves from 200MHz to 300MHz+ !
It's clear the the real issue is with Quartus being to dumb to recognize this structure by itself, but such is life...
On a Cyclone 4, the impact is neglible: ~30 logic elements Iess (out of 5700 in my case.)

Fast mul optimization

---

dhrystone/Makefile
dhrystone/testbench_slow_mem.v

'make test_slow_mem' to run dhrystone on a testbench that has FPGA memory with input registers and output registers on the memory itself enabled.
This is useful to assess performance for cases where you want to run the core at maximum speed possible, one of the stated goals of picorv32 :-). Without those input and output registers, the critical path is often in the memory.

dhrystone with registered memory

---

picorv32.v

This version is used for the packaged Vivado IP version. I just added the STACKADDR parameter to the picorv32_axi module so that we can modify it using the GUI in Vivado.

Add STACKADDR parameter to picorv32_axi module

---

picorv32.v
testbench_wb.v

Unification of testbench output makes it possible to use the diff
utility for comparing testbench instruction traces.
Alas the testbench and testbench_wb traces are differ
because of interrupts, e.g.
picorv32$ make testbench_wb.vvp
iverilog -o testbench_wb.vvp -DCOMPRESSED_ISA -DRISCV_FORMAL testbench_wb.v picorv32.v
chmod -x testbench_wb.vvp
picorv32$ make testbench.vvp
iverilog -o testbench.vvp -DCOMPRESSED_ISA -DRISCV_FORMAL testbench.v picorv32.v
chmod -x testbench.vvp
picorv32$ vvp -N testbench_wb.vvp +verbose | head -n 856 > /tmp/testbench_wb.log
picorv32$ vvp -N testbench.vvp +verbose | head -n 856 > /tmp/testbench.log
picorv32$ diff -u /tmp/testbench.log /tmp/testbench_wb.log
--- /tmp/testbench.log  2017-04-06 06:56:06.079804549 +0300
+++ /tmp/testbench_wb.log       2017-04-06 …

testbench_wb.v: unify verbose output with axi testbench

---

testbench_wb.v

Load firmware in testbench_wb from plusarg instead of parameter to allow selection at runtime. Also add attribution for wb_ram module, originally from https://github.com/fusesoc/wb_ram

Testbench wb fixes

---

scripts/icestorm/Makefile
scripts/quartus/Makefile
scripts/vivado/Makefile

Fixes deprecated usage of `-m32` for RISCV GCC, and hardcoded paths to `/usr/local` in favor of `yosys-config --datdir` (like `picosoc` does).

Small fixes to the IceStorm scripts

---

picorv32.core
testbench.cc

First patch adds a verilator testbench. This is the testbench from scripts/csmith but with added VCD generation
Second patch adds FuseSoC support for running testbenches and an additional lint target
FuseSoC support can be tested by first creating a workspace directory and register picorv32 as a library by running
fusesoc library add picorv32 https://github.com/cliffordwolf/picorv32
or, alternatively if the repo is already on disk and you want to use that instead, run
fusesoc library add picorv32 /path/to/repo
To list all targets supported by the picorv32 core, run `fusesoc core-info picorv32`. To run the standard testbench, use `fusesoc run --target=test --tool=<tool> picorv32 --firmware=/path/to/firmware.hex` where `<tool>` can be any of icarus, isim, modelsim, rivierapro, verilator or …

Verilator testbench and FuseSoC support

---

picosoc/sections.lds

added .data and .bss segments to picosoc firmware linker script so that static variables may be used.

add .data and .bss segments to picosoc

---

picosoc/picosoc.v

Previously, picosoc.v needed to be sourced before picorv32.v to
ensure that the PICORV32_REGS `define (used to select implementation
for the register file) was set to picosoc_regs
This allows for overriding PICORV32_REGS, e.g. by setting it
externally in the EDA tool invocation. In this case, the compile
order between picorv32.v and picosoc.v is not important.
Note: This change will break the safety check if PICORV32_REGS
is defined between sourcing picorv32.v and picosoc.v

Bypass picosoc compile order check if PICORV32_REGS is defined.

---

picosoc/hx8kdemo.core
picosoc/picosoc.core
picosoc/spiflash.core

Updated version of an old PR. The changes from the previous version is that the .core files now live in the picosoc directory as FuseSoC allows finding cores in subdirectories of other cores since version 1.8.3
Please note that due to a bug found after the 1.8.3 release which requires to specify `--target=default` in the cases where no explicit target was supplied on the command-line. This has been fixed in FuseSoC git master already but is not in a released version yet

Picosoc fusesoc v2

---

picosoc/Makefile
picosoc/firmware.c
picosoc/sections.lds

Created FLASH section (please update to proper size), and RAM (set that default of 1K that is in picosoc) 
No more need for using sed and tail inside Makefile.
Code from firmware.c can better be converted to asm and placed inside start.s

Created lds file (section mapping) and init for data and bss sections

---

picosoc/picosoc.v

This allows the @tinyfpga BX fork to use an unmodified upstream copy of picosoc.v

Expose ENABLE_IRQ_QREGS and PROGADDR_IRQ from picosoc.v

---

picosoc/icebreaker.core

Build with `fusesoc build icebreaker` or simulate with `fusesoc sim icebreaker --firmware=/path/to/icebreaker_fw.hex`. Icarus is default simulator. `fusesoc sim --sim=...` to use a different one

Add FuseSoC support for icebreaker

---

README.md

Current link to RISC-V tools ends up in 404 error page.
This change directs now to the page I believe to be the correct one.
I checked the whole README.md file, this is the only broken link I found.

Update Risc-V website link for tools

---

scripts/vivado/Makefile

This updates the Vivado scripts folder
- Update to use the 32 bit toolchain instead of the 64 bit one.
- Use current Vivado version(2018.2).

Update vivado scripts

---

.gitignore
scripts/icestorm/Makefile
scripts/icestorm/firmware.c
scripts/icestorm/readme.md
shell.nix

While packaging and updating various FOSS EDA tools for [NixOS](https://nixos.org), PicoRV32 has proven very useful for testing changes. In particular the icestorm demo is very useful in my experience due to its simplicity and while trying to test some NixOS changes, I did several touchups. In particular this:
- Makes the simulation vs hardware builds easier to run (I didn't realise `SHIFT_COUNTER_BITS` needed adjustment)
- Uses `nextpnr-ice40` instead of `arachne-pnr`, which gives better routing results.
- Adds a `timing` target.
- Tweaks the Makefile to use dependency variables (`$@`, `$^`, `$<`) more to make small tweaks/additions more robust and easier to hack.
- Fixes a bug where `-march=rv32i` was not explicitly set.
- Adds a `readme.md` for running things.
- Adds a `shell.nix` file …

Various touchups to scripts/icestorm demo

---

picosoc/.gitignore
picosoc/Makefile
picosoc/firmware.c
picosoc/ice40up5k_spram.v
picosoc/icebreaker.v
picosoc/icebreaker_tb.v
picosoc/picosoc.core
picosoc/picosoc.v
picosoc/sections.lds

This PR replaces the usage of automatically inferred BRAM cells with SPRAM on ICE40UP5K based boards like the Icebreaker. The available memory is thereby increased from 2 KiB to 128 KiB.
It also adds a simple memtest tool to the firmware.
The code is adapted from @daveshah1's [version for the UPDuino 5K board](https://github.com/daveshah1/picorv32/commit/b83970cac7431d0e05fc50a557e4a0845f9edfa0).
If there are no objections, I would like to merge @daveshah1's [up5k branch](https://github.com/daveshah1/picorv32/tree/up5k) afterwards.

Use SPRAM on ICE40UP5K based boards

---

picosoc/Makefile

Fix a typo that causes `make hx8kprog` to fail to build

fix typo in picosoc/Makefile for hx8k board

---

README.md

Just small doc change with picorv32_wb as third variation.

README.md: Also refer to picorv32_wb

---

Makefile
firmware/sections.lds

My freshly build toolchain fails to create a 4 bytes size aligned section.
The fix should be either in the firmware/sections.lds, or in the python script to automatically padding when not aligned with 4 bytes in size. Here it took the first approach.
Also modified slightly in Makefile how toolchain prefix is specified ... to allow easier adaptation by users.
For example, the installed riscv toolchain might not be called /opt/riscv32i, but rather /opt/riscv32/rv32i_ilp32, which requires two lines of modification ... Default path still preserved here.
A better implementation should have automatically detected if riscv gcc is already in search path, if not go and take env variable RISCV_PATH, and finally fallback to the Makefile default version ... but I really cannot write such complicated …

fix firmware/sections.lds section size alignment on 4 bytes

---

picosoc/Makefile

so one can run it with other toolchains, e.g.
CROSS=riscv64-t2-linux-gnu- CFLAGS=-mabi=ilp32, too

added CROSS prefix and CFLAGS to the picsoc/Makefile

---

picosoc/simpleuart.v

so that one can initialize it to a specific baud rate, or other special peripheral ones

added default clk divider parameter to simpleuart

---

picosoc/firmware.c

It destroys bss and data section memory.
You are not able to use static or global vars in firmware.c.

Workarround: Disable cmd_memtest() when starting firmware.

---

picosoc/README.md

According to https://github.com/cliffordwolf/picorv32/blob/c06ba38113b98b4996aed6d523667444a5d83bf6/picosoc/spimemio.v#L111 the reset value for `Read latency (dummy) cycles` is 8 cycles, not 0.

spimemio documentation: read latency reset value

---

picosoc/Makefile
picosoc/icebreaker.v
picosoc/picosoc.v

This patch splits the picosoc's `ENABLE_MULDIV` paramter into `ENABLE_MUL`, `ENABLE_DIV` and `ENABLE_FAST_MUL`,
and also enables the DSP-based fast multiplier for the iCE40up5k icebreaker board.

picosoc: enable fast multiply option for icebreaker

---

picosoc/Makefile

Updated hx8kdemo soc in /picosoc/Makefile to use nextpnr instead of arachne-pnr since its deprecated.

changed hx8kdemo from arachne-pnr to nextpnr-ice40

---

Makefile
README.md
picosoc/Makefile

Many Linux distributions now include the tools for RISC-V (for example
Ubuntu 20.04 has gcc-riscv64-unknown-elf) but in order for
make TOOLCHAIN_PREFIX=riscv64-unknown-elf-
to work we need to be explicit about compiling for 32-bit.

Enable the use of 64-bit riscv tools

---

README.md

I misunderstood the README and set `ENABLE_PCPI=1` when using an internal PCPI core. When built with Yosys, this caused the internal core to fail. This change clarifies that you should only use `ENABLE_PCPI=1` for external cores.
* ENABLE_PCPI is only needed for external co-processors.
* Correct spelling of demonstration.

Clarify use of ENABLE_PCPI

---

.github/workflows/ci.yml

Introduce Github Actions to run tests for PRs to avoid breaking changes.
Currently provides a `riscv-formal` job, using the oss-cad-suite to run the riscv-formal picorv32 checks.  Similar to the [riscv-formal CI](https://github.com/YosysHQ/riscv-formal/blob/main/.github/workflows/ci.yml) except we don't need to test NERV, and we want to test the current version of `picorv32.v` rather than the latest master.
Ideally we would also have a job for running `make test` etc, but setting up the riscv-gnu-toolchain is a bit more involved.

Adding ci.yml

---

scripts/cxxdemo/Makefile

`CCFLAGS` doesn't exist in my Make version as far as I'm aware.
I think it should be `CFLAGS`.
Here is a quick reference: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#index-CFLAGS

rename variable `CCFLAGS` to `CFLAGS`

---

firmware/start.S

This PR fixes the problem mentioned in Issue #210 .
The symbol `irq_regs` in `firmware/start.S` is possibly unaligned when compiled to support compressed instructions. However, `irq_regs` is further loaded into `sp` register and involved in memory access, which results in unaligned memory access problem.
This PR forces `irq_regs` to always be aligned with `.balign 0x200`, by doing this solves the problem.

firmware: fix unaligned symbol problem

---

picorv32.v

This fixes #211.
I haven't found any other broken instructions on RV32E, but I haven't done rigorous testing.
A cursory check suggests this change doesn't break the Q register instructions in RV32I, but I haven't tested that at all.

Fix RV32E shifts by immediates >= 0x10

---

picosoc/Makefile

picosoc: delete hx8kdemo.json when make clean is run
